if(EXISTS "/Users/dmitriikononov/Projects/bmstu_cpp_course/tasks/tasks/bmstu_lets/bmstu_lets[1]_tests.cmake")
  include("/Users/dmitriikononov/Projects/bmstu_cpp_course/tasks/tasks/bmstu_lets/bmstu_lets[1]_tests.cmake")
else()
  add_test(bmstu_lets_NOT_BUILT bmstu_lets_NOT_BUILT)
endif()
